// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztajnhhtknrohwetjfbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0YWpuaGh0a25yb2h3ZXRqZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjYyNjAsImV4cCI6MjA3NDA0MjI2MH0.Vf2zRM9KMqXKMlIqT_D47GDzmDtSvIBBf1tZ_KB4NpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});